name: milk_famer_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: 4.6.6
  permission_handler:
  dio: ^5.4.0
  get_storage: ^2.1.1
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.2.2
  flutter_downloader: ^1.11.6
  path_provider: ^2.1.1
  upgrader: ^9.0.0
  open_filex: ^4.4.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

flutter_native_splash:
  # color: "#5f6496"
  background_image: assets/images/background.jpeg
  # image: assets/images/bg.jpg
  # color_dark: "#1a1a1a"
  # image_darK: assets/icons/logo.png
  android: true
  ios: true
  web: true
  # android_gravity: center
  # ios_content_mode: center
  web_image_mode: center

  android_12:
    background_image: assets/images/background.jpeg
    # image: assets/images/makdairy1.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app.jpg"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/app.jpg"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
